[package]
authors = ["guillem.cordoba@gmail.com"]
edition = "2018"
name = "hc_zome_todo_rename"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "hc_zome_todo_rename"

[dependencies]
derive_more = "0"
serde = "1"

holo_hash = "0.0.2-alpha.1"
hdk = "0.0.100"
chrono = {version = "0.4", features = ["serde"]}
